name: LateralSource
favicon: null
layout_spectrum: 0.7734945402480662
typography_spectrum: 0.9370191008783877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.23080200050026178
  lightness: 0.47204151772893965
  saturation: 0.4802382111083716
  rhythmicContrast: 0.2759046475403011
purpose: []
